name: AWS example workflow

on:
  push

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: testing  # Referencing the "testing" environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Debug OIDC Token
        run: echo $ACTIONS_ID_TOKEN_REQUEST_URL
      - name: Debug Secret Access
        run: |
          if [ -z "${{ secrets.AWS_ROLE_TO_ASSUME }}" ]; then
            echo "Secret AWS_ROLE_TO_ASSUME is not available"
          else
            echo "Secret AWS_ROLE_TO_ASSUME is available"
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}  # Secret is linked to the "testing" environment
          aws-region: us-east-1
          role-session-name: cicd
          debug-logging: true

      - name: Test identity
        run: aws sts get-caller-identity
