name: AWS example workflow

on:
  push

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: testing  # Referencing the "testing" environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}  # Secret is linked to the "testing" environment
          aws-region: us-east-1

      - name: Test identity
        run: aws sts get-caller-identity
